# Generated by Django 5.0.2 on 2024-05-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_alter_documento_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.CharField(choices=[('General', 'General'), ('Circular', 'Circular'), ('Minuta', 'Minuta'), ('Nota', 'Nota'), ('Oficio', 'Oficio')], default='General', max_length=20),
        ),
    ]
